version: '1'
services:
  mariadb:
    image: mariadb
    container_name: 'fullstack-enter-mariadb'
    environment:
      MARIADB_ROOT_PASSWORD: '123456'
      MARIADB_DATABASE: 'fullstack_enter'
    ports:
      - 3306:3306
    restart: always
  redis:
    image: redis
    container_name: 'fullstack-enter-redis'
    ports:
      - 6379:6379
    restart: always